export * from './AbstractVariableInstruction'
export * from './GlobalGetInstruction'
export * from './GlobalSetInstruction'
export * from './GlobalVariableInstruction'
export * from './LocalGetInstruction'
export * from './LocalSetInstruction'
export * from './LocalTeeInstruction'
export * from './LocalVariableInstruction'
