export * from './AbstractCallInstruction'
export * from './CallIndirectInstruction'
export * from './CallInstruction'
export * from './ReturnCallIndirectInstruction'
export * from './ReturnCallInstruction'